### ISSUE TITLE
After destroying Fusionbox and setting back up, css files were not being updated after compilation.

### ISSUE THREAD

**Issue by mattpantoja** [efellemedia/fusionbox#6]
**Expected Result**
When compiling (using gulp) css files should be read by the local site and be visible after compilation.

**Actual Result**
Files compile without incident, but the most updated versions of the files would not be available to the local site.

**Resolution**
Editing the httpd.conf file ( fusionbox ssh, cd /etc/httpd/conf && sudo nano httpd.conf ) to EnableSendfile and then restarting the httpd service ( sudo service httpd restart ) seemed to resolve this issue. An ideal fix would be to update the fusionbox deployment to have this setting correct to begin with.

**Comment by kaidesu** [comment]
This is fixed in the latest fusionbox release~
